/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SalespersonForm.java
 *
 * Created on 27-Jan-2013, 13:50:27
 */

package application;

import validation.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.io.PrintWriter;
import java.text.DecimalFormat;
/**
 *
 * @author Evilguy
 */
public class SalespersonForm extends javax.swing.JFrame {

    //creating a list of Salesperson objects
    ArrayList<Salesperson> salespersonList = new ArrayList<Salesperson>();
    //creating a variable salesperson
    Salesperson varSalesperson = new Salesperson();
    //salesperson identificator
    int salespersonID = 0;
    //swing list
    DefaultListModel salespersonListInfo = new DefaultListModel();

    DecimalFormat df = new DecimalFormat("0.00");
    /** Creates new form SalespersonForm */
    public SalespersonForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstSalespersonList = new javax.swing.JList(salespersonListInfo);
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSalespersonInformation = new javax.swing.JPanel();
        txtPPSNumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        lblPPSNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        cboxCity = new javax.swing.JComboBox();
        cboxGender = new javax.swing.JComboBox();
        btnSaveAs = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlPayrollCalculation = new javax.swing.JPanel();
        txtCommissionPercent = new javax.swing.JTextField();
        txtPerItemSold = new javax.swing.JTextField();
        txtMinimalWage = new javax.swing.JTextField();
        lblCommissionPercent = new javax.swing.JLabel();
        lblStandardSalary = new javax.swing.JLabel();
        lblExtraPayPerYear = new javax.swing.JLabel();
        txtCommissionInEuro = new javax.swing.JTextField();
        txtSalaryPerWeek = new javax.swing.JTextField();
        lblSalaryPerYear = new javax.swing.JLabel();
        lblSalaryPerWeek = new javax.swing.JLabel();
        btnCalculatePayroll = new javax.swing.JButton();
        btnSaveInformationToFile = new javax.swing.JButton();
        btnSavePayroll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaInfo = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        lstSalespersonList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstSalespersonList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSalespersonListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstSalespersonList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 50, 160, 310);

        pnlSalespersonInformation.setLayout(null);

        txtPPSNumber.setText("1234567H");
        txtPPSNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPPSNumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPPSNumberKeyTyped(evt);
            }
        });
        pnlSalespersonInformation.add(txtPPSNumber);
        txtPPSNumber.setBounds(120, 30, 130, 20);

        txtName.setText("Vladislavs");
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        pnlSalespersonInformation.add(txtName);
        txtName.setBounds(120, 60, 130, 20);

        txtSurname.setText("Salesperson");
        txtSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSurnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSurnameKeyTyped(evt);
            }
        });
        pnlSalespersonInformation.add(txtSurname);
        txtSurname.setBounds(120, 90, 130, 20);

        txtAddress.setText("127 new castle");
        pnlSalespersonInformation.add(txtAddress);
        txtAddress.setBounds(120, 150, 130, 20);

        txtDateOfBirth.setText("07/12/1989");
        txtDateOfBirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDateOfBirthKeyTyped(evt);
            }
        });
        pnlSalespersonInformation.add(txtDateOfBirth);
        txtDateOfBirth.setBounds(120, 210, 130, 20);

        lblPPSNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPPSNumber.setText("PPS Number:");
        pnlSalespersonInformation.add(lblPPSNumber);
        lblPPSNumber.setBounds(10, 30, 100, 20);

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");
        pnlSalespersonInformation.add(lblName);
        lblName.setBounds(10, 60, 100, 20);

        lblSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSurname.setText("Surname:");
        pnlSalespersonInformation.add(lblSurname);
        lblSurname.setBounds(10, 90, 100, 20);

        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");
        pnlSalespersonInformation.add(lblGender);
        lblGender.setBounds(10, 120, 100, 20);

        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress.setText("Address:");
        pnlSalespersonInformation.add(lblAddress);
        lblAddress.setBounds(10, 150, 100, 20);

        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City:");
        pnlSalespersonInformation.add(lblCity);
        lblCity.setBounds(10, 180, 100, 20);

        lblDateOfBirth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateOfBirth.setText("Date of birth:");
        pnlSalespersonInformation.add(lblDateOfBirth);
        lblDateOfBirth.setBounds(10, 210, 100, 20);

        cboxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Kilkenny", "Wexford", "Sligo", "Clonmel", "Co.Dublin", "Co.Cork", "Co.Limerick", "Co.Galway", "Co.Waterford", "Co.Drogheda", "Co.Kilkenny", "Co.Wexford", "Co.Sligo", "Co.Clonmel" }));
        pnlSalespersonInformation.add(cboxCity);
        cboxCity.setBounds(120, 180, 130, 20);

        cboxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        pnlSalespersonInformation.add(cboxGender);
        cboxGender.setBounds(120, 120, 130, 20);

        btnSaveAs.setText("Save As");
        btnSaveAs.setMaximumSize(new java.awt.Dimension(80, 30));
        btnSaveAs.setMinimumSize(new java.awt.Dimension(80, 30));
        btnSaveAs.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });
        pnlSalespersonInformation.add(btnSaveAs);
        btnSaveAs.setBounds(50, 250, 80, 30);

        btnSave.setText("Save");
        btnSave.setMaximumSize(new java.awt.Dimension(80, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(80, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(80, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlSalespersonInformation.add(btnSave);
        btnSave.setBounds(130, 250, 80, 30);

        btnCancel.setText("Cancel");
        btnCancel.setMaximumSize(new java.awt.Dimension(80, 30));
        btnCancel.setMinimumSize(new java.awt.Dimension(80, 30));
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 30));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlSalespersonInformation.add(btnCancel);
        btnCancel.setBounds(210, 250, 80, 30);
        pnlSalespersonInformation.add(jPanel2);
        jPanel2.setBounds(0, -20, 10, 10);

        jTabbedPane1.addTab("Salesperson Information", pnlSalespersonInformation);

        pnlPayrollCalculation.setLayout(null);

        txtCommissionPercent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCommissionPercentKeyTyped(evt);
            }
        });
        pnlPayrollCalculation.add(txtCommissionPercent);
        txtCommissionPercent.setBounds(240, 90, 100, 20);

        txtPerItemSold.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPerItemSoldKeyTyped(evt);
            }
        });
        pnlPayrollCalculation.add(txtPerItemSold);
        txtPerItemSold.setBounds(240, 120, 100, 20);

        txtMinimalWage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinimalWageKeyTyped(evt);
            }
        });
        pnlPayrollCalculation.add(txtMinimalWage);
        txtMinimalWage.setBounds(240, 150, 100, 20);

        lblCommissionPercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommissionPercent.setText("Commission percent:");
        pnlPayrollCalculation.add(lblCommissionPercent);
        lblCommissionPercent.setBounds(40, 90, 180, 20);

        lblStandardSalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStandardSalary.setText("Summary price of sold items:");
        pnlPayrollCalculation.add(lblStandardSalary);
        lblStandardSalary.setBounds(40, 120, 180, 20);

        lblExtraPayPerYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblExtraPayPerYear.setText("Minimal wage:");
        pnlPayrollCalculation.add(lblExtraPayPerYear);
        lblExtraPayPerYear.setBounds(40, 150, 180, 20);

        txtCommissionInEuro.setEditable(false);
        pnlPayrollCalculation.add(txtCommissionInEuro);
        txtCommissionInEuro.setBounds(240, 180, 100, 20);

        txtSalaryPerWeek.setEditable(false);
        pnlPayrollCalculation.add(txtSalaryPerWeek);
        txtSalaryPerWeek.setBounds(240, 210, 100, 20);

        lblSalaryPerYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalaryPerYear.setText("Commission in euros:");
        pnlPayrollCalculation.add(lblSalaryPerYear);
        lblSalaryPerYear.setBounds(40, 180, 180, 20);

        lblSalaryPerWeek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalaryPerWeek.setText("Salary per week:");
        pnlPayrollCalculation.add(lblSalaryPerWeek);
        lblSalaryPerWeek.setBounds(40, 210, 180, 20);

        btnCalculatePayroll.setText("Calculate");
        btnCalculatePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculatePayrollActionPerformed(evt);
            }
        });
        pnlPayrollCalculation.add(btnCalculatePayroll);
        btnCalculatePayroll.setBounds(130, 250, 110, 40);

        btnSaveInformationToFile.setText("Save to file");
        btnSaveInformationToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInformationToFileActionPerformed(evt);
            }
        });
        pnlPayrollCalculation.add(btnSaveInformationToFile);
        btnSaveInformationToFile.setBounds(240, 250, 110, 40);

        btnSavePayroll.setText("Save");
        btnSavePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePayrollActionPerformed(evt);
            }
        });
        pnlPayrollCalculation.add(btnSavePayroll);
        btnSavePayroll.setBounds(20, 250, 110, 40);

        jTabbedPane1.addTab("Payroll Calculation", pnlPayrollCalculation);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 30, 370, 330);

        tAreaInfo.setBackground(new java.awt.Color(0, 0, 0));
        tAreaInfo.setColumns(20);
        tAreaInfo.setEditable(false);
        tAreaInfo.setFont(new java.awt.Font("Courier New", 0, 12));
        tAreaInfo.setForeground(new java.awt.Color(204, 204, 204));
        tAreaInfo.setRows(5);
        jScrollPane2.setViewportView(tAreaInfo);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 370, 560, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPPSNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSNumberKeyTyped
        // TODO add your handling code here:
        datavalidation.ppsValidation(evt);
    }//GEN-LAST:event_txtPPSNumberKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        // TODO add your handling code here:
        datavalidation.nameValidation(evt);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtSurnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyTyped
        // TODO add your handling code here:
        datavalidation.nameValidation(evt);
    }//GEN-LAST:event_txtSurnameKeyTyped

    private void txtDateOfBirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDateOfBirthKeyTyped
        // TODO add your handling code here:
        datavalidation.dateValidation(evt);
    }//GEN-LAST:event_txtDateOfBirthKeyTyped

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        autocorrection.nameCorrection(txtName);
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtSurnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSurnameKeyReleased
        // TODO add your handling code here:
        autocorrection.nameCorrection(txtSurname);
    }//GEN-LAST:event_txtSurnameKeyReleased

    private void txtPPSNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPPSNumberKeyReleased
        // TODO add your handling code here:
        autocorrection.ppsCorrection(txtPPSNumber);
    }//GEN-LAST:event_txtPPSNumberKeyReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // erase all fields
        txtPPSNumber.setText("");
        txtName.setText("");
        txtSurname.setText("");
        txtAddress.setText("");
        txtDateOfBirth.setText("");
        cboxGender.setSelectedIndex(0);
        cboxCity.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        /*
        txtPPSNumber
        txtName
        txtSurname
        cboxGender
        txtAddress
        cboxCity
        txtDateOfBirth
        */

        varSalesperson.setPPSNumbers(txtPPSNumber.getText());
        varSalesperson.setName(txtName.getText());
        varSalesperson.setSurname(txtSurname.getText());
        varSalesperson.setGender(cboxGender.getSelectedIndex());
        varSalesperson.setAddress(txtAddress.getText());
        varSalesperson.setCity(cboxCity.getSelectedIndex());
        varSalesperson.setDoB(txtDateOfBirth.getText());

        if (!(txtPPSNumber.getText().isEmpty())
                && !(txtName.getText().isEmpty())
                && !(txtSurname.getText().isEmpty())
                && !(txtAddress.getText().isEmpty())
                && (varSalesperson.checkDob(txtDateOfBirth.getText()))){

            //trying to update the object in array list
            //if cause an error it creates a new object
            try{
                salespersonList.set(salespersonID, varSalesperson);
            }catch (Exception e){
                salespersonList.add(varSalesperson);
            }

            //trying to update the element in swing jList
            //if caused an error it creates new element
            try{
            salespersonListInfo.setElementAt(varSalesperson.getName() + " " + varSalesperson.getSurname(), salespersonID);
            }catch (Exception e){
            salespersonListInfo.addElement(varSalesperson.getName() + " " + varSalesperson.getSurname());
            }

            //writing some information to log area
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Salesperson with name: "+ varSalesperson.getName()
                + " " + varSalesperson.getSurname() + ", has been saved to array. With ID " + salespersonID);
        } else {
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Can not save the information, please fill all information");
        }
        varSalesperson = new Salesperson();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
        // TODO add your handling code here:
        varSalesperson.setPPSNumbers(txtPPSNumber.getText());
        varSalesperson.setName(txtName.getText());
        varSalesperson.setSurname(txtSurname.getText());
        varSalesperson.setGender(cboxGender.getSelectedIndex());
        varSalesperson.setAddress(txtAddress.getText());
        varSalesperson.setCity(cboxCity.getSelectedIndex());
        varSalesperson.setDoB(txtDateOfBirth.getText());

        salespersonID = salespersonList.size();
        if (!(txtPPSNumber.getText().isEmpty())
                && !(txtName.getText().isEmpty())
                && !(txtSurname.getText().isEmpty())
                && !(txtAddress.getText().isEmpty())
                && (varSalesperson.checkDob(txtDateOfBirth.getText()))){

            //trying to update the object in array list
            //if cause an error it creates a new object
            
                salespersonList.add(salespersonID, varSalesperson);
            

            //trying to update the element in swing jList
            //if caused an error it creates new element
           // lstSalespersonList.clearSelection();
           
            
            salespersonListInfo.addElement(varSalesperson.getName() + " " + varSalesperson.getSurname());
            

            //writing some information to log area
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Salesperson with name: "+ varSalesperson.getName()
                + " " + varSalesperson.getSurname() + ", has been saved to array. With ID " + salespersonID);
                
        } else {
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Can not save the information, please fill all information");
            
        }
        varSalesperson = new Salesperson();
    }//GEN-LAST:event_btnSaveAsActionPerformed

    private void lstSalespersonListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSalespersonListValueChanged
        // TODO add your handling code here:
        varSalesperson = new Salesperson();
        salespersonID = lstSalespersonList.getSelectedIndex();
        varSalesperson = salespersonList.get(salespersonID);
        //print out the information about salesperson
        txtPPSNumber.setText(varSalesperson.getPPSNumber());
        txtName.setText(varSalesperson.getName());
        txtSurname.setText(varSalesperson.getSurname());
        cboxGender.setSelectedIndex(varSalesperson.getGender());
        txtAddress.setText(varSalesperson.getAddress());
        cboxCity.setSelectedIndex(varSalesperson.getCity());
        txtDateOfBirth.setText(varSalesperson.getDoB());
        //print out the information about salesperson's payroll
        txtCommissionPercent.setText(""+varSalesperson.getCommissionPercent());
        txtPerItemSold.setText(df.format(varSalesperson.getPerItemSold()));
        txtMinimalWage.setText(df.format(varSalesperson.getMinimalWage()));
        //clear the information about salary
        txtCommissionInEuro.setText("");
        txtSalaryPerWeek.setText("");
       

    }//GEN-LAST:event_lstSalespersonListValueChanged

    private void btnSavePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePayrollActionPerformed
        // TODO add your handling code here:


        try{
        varSalesperson = salespersonList.get(salespersonID);
        varSalesperson.setCommissionPercent(txtCommissionPercent.getText());
        varSalesperson.setPerItemSold(txtPerItemSold.getText());
        varSalesperson.setMinimalWage(txtMinimalWage.getText());

        if (!(txtCommissionPercent.getText().isEmpty())
                && !(txtPerItemSold.getText().isEmpty())
                && !(txtMinimalWage.getText().isEmpty())){
        salespersonList.set(salespersonID, varSalesperson);
        tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"payroll information has been updated. To salesperson with this " + salespersonID + " ID.");
        } else {
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Can not save the information, please fill all information about payroll");

        }
        varSalesperson = new Salesperson();
        } catch (Exception e){
        tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Can not save the information, please please select a person from list");
        }
    }//GEN-LAST:event_btnSavePayrollActionPerformed


    private void btnCalculatePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculatePayrollActionPerformed
        // TODO add your handling code here:
        try {
        btnSavePayroll.doClick();
        varSalesperson = salespersonList.get(salespersonID);

        txtCommissionInEuro.setText(df.format(varSalesperson.getCommissionInEuro()));
        txtSalaryPerWeek.setText(df.format(varSalesperson.getFullWage()));

        tAreaInfo.setText(tAreaInfo.getText() +"\n" +
                "Calculation of salary");
        varSalesperson = new Salesperson();
        }catch (Exception e){
        tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"cannot calculate the payroll...");
        }

    }//GEN-LAST:event_btnCalculatePayrollActionPerformed

    private void txtCommissionPercentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommissionPercentKeyTyped
        // TODO add your handling code here:
        datavalidation.currencyValidation(evt);
    }//GEN-LAST:event_txtCommissionPercentKeyTyped

    private void txtPerItemSoldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPerItemSoldKeyTyped
        // TODO add your handling code here:
        datavalidation.currencyValidation(evt);
    }//GEN-LAST:event_txtPerItemSoldKeyTyped

    private void txtMinimalWageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinimalWageKeyTyped
        // TODO add your handling code here:
        datavalidation.currencyValidation(evt);
    }//GEN-LAST:event_txtMinimalWageKeyTyped

    private void btnSaveInformationToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInformationToFileActionPerformed
        // TODO add your handling code here:
        
            try{
            varSalesperson = salespersonList.get(salespersonID);
            PrintWriter writer =new PrintWriter("TXTFILES/"+varSalesperson.getName()+varSalesperson.getSurname()+".txt");
            writer.println("\t\tSalesperson's salary calculation");
            writer.println("\tName\t\t\t\t "+varSalesperson.getName());
            writer.println("\tSurname\t\t\t\t "+varSalesperson.getSurname());
            writer.println("\tCommission percent\t\t "+varSalesperson.getCommissionPercent());
            writer.println("\tPer item sold\t\t\t "+df.format(varSalesperson.getPerItemSold()));
            writer.println("\tMinimal wage\t\t\t "+df.format(varSalesperson.getMinimalWage()));
            writer.println("\tCommission in euro\t\t "+df.format(varSalesperson.getCommissionInEuro()));
            writer.print("\tSalary per Week\t\t "+df.format(varSalesperson.getFullWage()));

            writer.flush();
            writer.close();
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"Information was saved sucessfully. in TXTFILES/"+varSalesperson.getName()+varSalesperson.getSurname()+".txt");
            } catch (Exception e){
            tAreaInfo.setText(tAreaInfo.getText() +"\n"
                +"cannot save the file...");
            }
    }//GEN-LAST:event_btnSaveInformationToFileActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalespersonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculatePayroll;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnSaveInformationToFile;
    private javax.swing.JButton btnSavePayroll;
    private javax.swing.JComboBox cboxCity;
    private javax.swing.JComboBox cboxGender;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommissionPercent;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblExtraPayPerYear;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPPSNumber;
    private javax.swing.JLabel lblSalaryPerWeek;
    private javax.swing.JLabel lblSalaryPerYear;
    private javax.swing.JLabel lblStandardSalary;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JList lstSalespersonList;
    private javax.swing.JPanel pnlPayrollCalculation;
    private javax.swing.JPanel pnlSalespersonInformation;
    private javax.swing.JTextArea tAreaInfo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCommissionInEuro;
    private javax.swing.JTextField txtCommissionPercent;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtMinimalWage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPPSNumber;
    private javax.swing.JTextField txtPerItemSold;
    private javax.swing.JTextField txtSalaryPerWeek;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

}
