/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * STARTME.java
 *
 * Created on 29-Jan-2013, 15:11:24
 */

package application;

/**
 *
 * @author Evilguy
 */
public class STARTME extends javax.swing.JFrame {

    ManagerForm mf = new ManagerForm();
    CashierForm cf = new CashierForm();
    SalespersonForm sf = new SalespersonForm();
    /** Creates new form STARTME */
    public STARTME() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManager = new javax.swing.JButton();
        btnCashier = new javax.swing.JButton();
        btnSalesperson = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retail Store System");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(305, 210));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        btnManager.setText("Manager");
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnManager);
        btnManager.setBounds(170, 10, 120, 23);

        btnCashier.setText("Cashier");
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashier);
        btnCashier.setBounds(170, 40, 120, 23);

        btnSalesperson.setText("Salesperson");
        btnSalesperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalespersonActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalesperson);
        btnSalesperson.setBounds(170, 70, 120, 23);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(170, 100, 120, 23);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Povesti cu Tom si Jerry.jpg"))); // NOI18N
        lblImage.setAlignmentY(0.0F);
        jPanel1.add(lblImage);
        lblImage.setBounds(0, 0, 300, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mf.setVisible(false);
        cf.setVisible(false);
        sf.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        // TODO add your handling code here:
        if(!(mf.isVisible())){
        mf.setVisible(true);
        }
        if(cf.isVisible()){
            cf.setVisible(false);
        }
        if(sf.isVisible()){
            sf.setVisible(false);
        }

    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        // TODO add your handling code here:
        if(!(cf.isVisible())){
        cf.setVisible(true);
        }
        if(mf.isVisible()){
            mf.setVisible(false);
        }
        if(sf.isVisible()){
            sf.setVisible(false);
        }
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnSalespersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalespersonActionPerformed
        // TODO add your handling code here:
        if(!(sf.isVisible())){
        sf.setVisible(true);
        }
        if(mf.isVisible()){
            mf.setVisible(false);
        }
        if(cf.isVisible()){
            cf.setVisible(false);
        }
    }//GEN-LAST:event_btnSalespersonActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        mf.dispose();
        cf.dispose();
        sf.dispose();
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STARTME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnSalesperson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables

}
